// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '[id]': typeof import('./src/components/[id].vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    Cart: typeof import('./src/components/cart.vue')['default']
    Gallery: typeof import('./src/components/gallery.vue')['default']
    GridContent: typeof import('./src/components/GridContent.vue')['default']
    IMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiGoogle: typeof import('~icons/mdi/google')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    Lightbox: typeof import('./src/components/lightbox.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    PromotionalSections: typeof import('./src/components/PromotionalSections.vue')['default']
    SkeletonProduct: typeof import('./src/components/SkeletonProduct.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLabel: typeof import('./src/components/VLabel.vue')['default']
    VPasswordInput: typeof import('./src/components/VPasswordInput.vue')['default']
  }
}

export { }
